config/routes.rb
Rails.application.routes.draw do



  resources :categories
 root 'pages#index'
resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	
	has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord

	validates :name, presence: true

	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index

  	@posts = Post.all
  end

  def show
  
  end

   def edit
  
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new()
  	if @post.update(params.require(:post).permit(:name, :content))
  	 redirect_to posts_url, notice: "L'article a bien été crée"
    else
      render :new
    end
  end

  def update
  
    if @post.update(post_params)
    	redirect_to posts_url, notice: "L'article a bien été modifié"
    else
      render :edit
    end
  end

  def destroy
  	
  	@post.destroy
  	redirect_to posts_url, notice: "L'article a bien été supprimé"
  end

  private

  def set_post

  	@post = Post.find(params[:id])
  end

  def post_params
  	params.require(:post).permit(:name, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>kingwatson the very best men</h1>

app/views/posts/_form.html.erb
<%= simple_form_for post do |f| %>

	<%= f.input :name  %>
	<%= f.input :content  %>
	<%= f.button :submit, post.new_record? ? 'Creer' : 'Modifier' %>

<% end %>

app/views/posts/edit.html.erb
<h1>Editer un article</h1>

<%= render 'form', post: @post  %>

app/views/posts/index.html.erb
<h1>Articles</h1>

<% if flash[:notice] %>
	<div class="alert alert-success">

		<%= flash[:notice] %>
	</div>
<% end %>

<ul>
	<% @posts.each do |post| %>
		<li>
			<%= link_to post.name, post_path(post) %> -
			<%= link_to 'editer', [:edit, post] %>	-
			<%= link_to 'supprimer',post, method: :delete ,data: {confirm: 'vous etes sur de vouloir supprimer'} %>			
		</li>
	<% end %>
</ul>

<%= link_to 'Créer un article', new_post_path %>

app/views/posts/new.html.erb
<h1>Cree un article</h1>

<%= render 'form', post: @post  %>

app/views/posts/show.html.erb
<p><%= link_to 'Revenir aux articles', Post %></p>

<h1><%= @post.name %></h1>

<%= @post.content %>